### PR TITLE
Update conversions.jl

### PR DESCRIPTION
**Pull request by sbromberger**
See #201.

### CODE REVIEW

**Comment by stevengj** [comment]
You know, you can do a forced push (after squashing commits) to update an existing PR, rather than creating a new PR...

**Comment by sbromberger** [comment]
Understood, but I don't know how to squash commits when the files were edited within the github.com editor.

**Comment by stevengj** [comment]
Can you add a test? Just convert(BigInt, PyObject(1234)) == 1234 will test this function.

**Comment by sbromberger** [comment]
Sure, but I won't be able to squash the commits...

**Pull request merged**
