### PR TITLE
Fix dict filter by removing `items`, Fix tests for v0.3 compat

### PR DESCRIPTION
**Pull request by ranjanan**
Fix the function `filter!()` by removing `items(d)`

### CODE REVIEW

**Comment by ranjanan** [comment]
This should fix #226

**Comment by ranjanan** [comment]
@tkelman Could you please help with code review?

**Comment by ranjanan** [comment]
The Appveyor build fails because of [this](https://github.com/stevengj/PyCall.jl/blob/master/test/runtests.jl#L41). There needs to be an `@compat` there for all the `UInt8`'s. But I'm curious about why Appveyor checks against v0.3 while Travis checks against v0.4

**Comment by tkelman** [comment]
The [.travis.yml file here](https://github.com/stevengj/PyCall.jl/blob/master/.travis.yml) is still using the PPA for installing Julia, which does not make it very easy to install 0.3 any more. You can't use multiple `language:` settings, and it's a little more effort to install specific versions of Python than it is specific versions of Julia. The Travis file could be reformatted to download the generic Linux binaries (and osx dmg installers if osx is running) instead of the PPA to restore testing against 0.3.

**Comment by ranjanan** [comment]
I see. Maybe I should modify Travis to do pull the v0.3 binaries and send a separate PR. Also, the above commit fixes #228

**Comment by stevengj** [comment]
Doing `for (k,v) in d` uses the dictionary iterator, which calls `PyDict_Next`.  The [documentation for the latter function](https://docs.python.org/3.2/c-api/dict.html) explicitly says "The dictionary `p` should not be mutated during iteration"

Hence, I don't think this change is a good idea; there must be a more reliable way to fix it.

**Comment by stevengj** [comment]
Two options that I can see:

* Replace `items(d)` (which must have gotten removed from Julia at some point) by e.g. `collect(Tuple{PyObject,PyObject}, d)`.  This unfortunately makes a copy of the data.
* Do `for (k,v) in d` or similar, but instead of deleting the keys right away, `push!` them to a temporary array of keys to be deleted.   This is a bit more memory-efficient for large dictionaries.

**Comment by stevengj** [comment]
Fixed by 73c3db71e8e1eca4ef1e950e5aaabe65f544b159

**Pull request closed without merging**
