### PR TITLE
Fix build.jl depwarns

### PR DESCRIPTION
**Pull request by ranjanan**
Fixes the deprecated OS macros. 

(NOTE: Compat is already at an appropriate minimum version)

### CODE REVIEW

**Comment by ranjanan** [comment]
Okay, 32-bit nightly failed because it couldn't connect to server and download something.

**Comment by ranjanan** [comment]
Thank you! Would you mind tagging a new release please?

**Comment by ranjanan** [comment]
@stevengj Now that #303 has been merged, could you please tag a new release?

**Comment by stevengj** [comment]
1.7.1 tag is pending.

**Pull request merged**
