### PR TITLE
Fix julia 0.5 deprecation warnings

### PR DESCRIPTION
**Pull request by davidanthoff**
Would be great to tag another version once this is merged.

This fixes deprecation warnings that show up during precompile.

### CODE REVIEW

**Comment by stevengj** [comment]
The AppVeyor failure is a bit mysterious to me...

**Comment by davidanthoff** [comment]
Yeah, especially hard to see how any of the changes in this PR could cause this...

**Comment by stevengj** [comment]
Maybe try a rebase and forced push to see if this was an temporary problem with Julia nightly or AppVeyor?

**Comment by stevengj** [comment]
Okay, now `master` is failing on AppVeyor, so I don't think it's this PR.

**Pull request merged**
