### PR TITLE
Added ability to reuse local dictionary across calls to pyeval

### PR DESCRIPTION
**Pull request by malmaud**
This makes it possible to call ``pyeval`` with class definitions and then later refer to those class definitions in a subsequent call to ``pyeval``.

### CODE REVIEW

**Comment by stevengj** [comment]
Looks good, thanks.

I've been thinking that it might be nice to have a
```py"""
....
"""
```
string macro that corresponds to `pyeval` with `Py_file_input`.  Maybe with `$...` interpolation in the form of generated local variables.

**Comment by malmaud** [comment]
Similar to an IPython %%julia magic cell, but in reverse? That would be quite cool.

**Comment by utensil** [comment]
I haven't found any document or comment to explain how to use this functionality. Am I missing something?

**Comment by stevengj** [comment]
@utensil, call `pyeval` with `Py_file_input` as the fourth parameter.

**Comment by utensil** [comment]
@stevengj Thanks for the explanation. I did see the intent expressed in the function signature, and I'm aware of [Py_eval_input/Py_single_input/Py_file_input](https://docs.python.org/2/c-api/veryhigh.html). 

"reuse local dictionary across calls to pyeval" as how it literally sounds is what I needed. But this title, the description and the implementation, all together didn't make any sense to me, so I looking for the actual usage as sample code to verify, or some further explanations.

**Comment by utensil** [comment]
I find some other way to implement what I need, but when combining with these flags like `Py_file_input` and `Py_single_input`, it gives different results:

image

**Comment by utensil** [comment]
The example above might be related to the library I'm using, so I created a minimal reproduction of this.

image


```julia
vara = 1;varb = 2;
local_vars = PyDict(Dict(:vara=>vara, :varb=>varb))
PyCall.pyeval_("vara + varb", local_vars, PyCall.Py_eval_input) # or single or file
```

It seems that:

* `Py_eval_input` returns an object of 3
* `Py_single_input` prints 3 to STDOUT, and returns an object of None
* `Py_file_input` return an object of None

**Comment by stevengj** [comment]
That's right.  Only `Py_eval_input` returns the result of a expression.   To return the result of the last expression like in IPython it seems we have to parse the string expression by expression, see #255

**Comment by utensil** [comment]
Oh yes, #255 is the right issue for me to track.

**Comment by stevengj** [comment]
f07f94db7c690073ee738379494341c4276cdea7 now adds the `py"..."` syntax, and `pyeval` is deprecated.   `$` interpolation syntax is now used to pass Julia variables (as converted values — this is not string interpolation, despite the resemblance).   If you use a multi-line string, then it uses `Py_file_input` (in the global `__main__` Python namespace), so you can define Python classes, functions, etcetera and refer to them in subsequent `py"..."` strings.  e.g.

```jl
julia> py"""
       def foo(x):
           return x + 1
       """

julia> x = 17
17

julia> py"foo"(x)
18

julia> py"foo($x)"
18
```

**Pull request merged**
