### PR TITLE
correct deprecated function

### PR DESCRIPTION
**Pull request by Roger-luo**
My SymPy.jl failed to build with this warning:

```
julia> using SymPy
WARNING: get_bigfloat_precision() is deprecated, use precision(BigFloat) instead.
 [inlined code] from ./error.jl:26
 in depwarn(::ASCIIString, ::Symbol) at ./deprecated.jl:64
 in get_bigfloat_precision() at ./deprecated.jl:50
 in mpmath_init() at /home/roger/.julia/v0.5/PyCall/src/conversions.jl:610
 in init_mpmath() at /home/roger/.julia/v0.5/SymPy/src/mpmath.jl:43
 in __init__() at /home/roger/.julia/v0.5/SymPy/src/SymPy.jl:315
 in _require_from_serialized(::Int64, ::Symbol, ::ASCIIString, ::Bool) at ./loading.jl:165
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at ./loading.jl:193
 in require(::Symbol) at ./loading.jl:323
 in eval(::Module, ::Any) at ./boot.jl:237
while loading no file, in expression starting on line 0
```

After correct this line, it somehow works just fine.

### CODE REVIEW

**Comment by stevengj** [comment]
That's odd, a deprecation warning should cause a build failure...

**Comment by stevengj** [comment]
You need to edit the REQUIRE file to increase the required Compat version to 0.7.10 (which is when the compatibility for `get_bigfloat_precision` was introduced).

**Comment by stevengj** [comment]
Looks good to merge, can you do a `git rebase` followed by a forced push, to squash this into a single commit?

**Comment by stevengj** [comment]
You need to do `git rebase -i` to squash the commits into a single commit.  See e.g.:

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by Roger-luo** [comment]
Sorry, does it work now?

**Comment by stevengj** [comment]
@Roger-luo: No, you'll notice at the top of the PR that it is listed as 16 commits.  The goal of squashing is to combine it into a single commit, so that the PR says "1 commit".

**Comment by stevengj** [comment]
Also, for some reason this PR includes other unrelated commits from the tree, so probably you made a mistake in the rebase.   It might be easiest to just start with a clean branch and re-apply your patch.

**Comment by Roger-luo** [comment]
sure

**Pull request closed without merging**
